apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-custom-alert
  namespace: observability
spec:
  groups:
    - name: test
      rules:
        - alert: TestCustomAlert
          expr: vector(1)
          for: 30s
          labels:
            severity: warning
          annotations:
            summary: "TEST custom alert"
            description: "Always firing test alert"
